//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ClaimIndemnity_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimIndemnity_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimIndemSeq" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ClaimObjectSeq" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ClaimID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}RequestNo" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}InsuredObjectID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}CoverCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}RiskType" minOccurs="0"/>
 *         &lt;element name="InspectNum" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="IndemnityType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ConvertDateType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ConvertDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CalculateDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="PaySum" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Currency"/>
 *         &lt;element name="CalSum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CorrectReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OverLimit" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}UpdatedBy" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}UpdatedOn" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}CustomProperties" minOccurs="0"/>
 *         &lt;element name="ClaimIndeminityDetails" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ClaimIndeminityDetails_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimIndemnity_Type", propOrder = {
    "claimIndemSeq",
    "claimObjectSeq",
    "claimID",
    "requestNo",
    "insuredObjectID",
    "coverCode",
    "riskType",
    "inspectNum",
    "indemnityType",
    "convertDateType",
    "convertDate",
    "calculateDate",
    "paySum",
    "currency",
    "calSum",
    "correctReason",
    "overLimit",
    "updatedBy",
    "updatedOn",
    "customProperties",
    "claimIndeminityDetails"
})
public class ClaimIndemnityType {

    @XmlElement(name = "ClaimIndemSeq")
    protected Long claimIndemSeq;
    @XmlElement(name = "ClaimObjectSeq")
    protected Long claimObjectSeq;
    @XmlElement(name = "ClaimID")
    protected String claimID;
    @XmlElement(name = "RequestNo")
    protected BigInteger requestNo;
    @XmlElement(name = "InsuredObjectID")
    protected Long insuredObjectID;
    @XmlElement(name = "CoverCode")
    protected String coverCode;
    @XmlElement(name = "RiskType")
    protected String riskType;
    @XmlElement(name = "InspectNum")
    protected BigInteger inspectNum;
    @XmlElement(name = "IndemnityType", required = true)
    protected BigInteger indemnityType;
    @XmlElement(name = "ConvertDateType")
    protected int convertDateType;
    @XmlElement(name = "ConvertDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar convertDate;
    @XmlElement(name = "CalculateDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar calculateDate;
    @XmlElement(name = "PaySum")
    protected double paySum;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "CalSum")
    protected Double calSum;
    @XmlElement(name = "CorrectReason")
    protected String correctReason;
    @XmlElement(name = "OverLimit")
    protected Integer overLimit;
    @XmlElement(name = "UpdatedBy")
    protected String updatedBy;
    @XmlElement(name = "UpdatedOn")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedOn;
    @XmlElement(name = "CustomProperties")
    protected CustomPropertiesType customProperties;
    @XmlElement(name = "ClaimIndeminityDetails")
    protected ClaimIndeminityDetailsType claimIndeminityDetails;

    /**
     * Gets the value of the claimIndemSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClaimIndemSeq() {
        return claimIndemSeq;
    }

    /**
     * Sets the value of the claimIndemSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClaimIndemSeq(Long value) {
        this.claimIndemSeq = value;
    }

    /**
     * Gets the value of the claimObjectSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClaimObjectSeq() {
        return claimObjectSeq;
    }

    /**
     * Sets the value of the claimObjectSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClaimObjectSeq(Long value) {
        this.claimObjectSeq = value;
    }

    /**
     * Gets the value of the claimID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimID() {
        return claimID;
    }

    /**
     * Sets the value of the claimID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimID(String value) {
        this.claimID = value;
    }

    /**
     * Gets the value of the requestNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestNo() {
        return requestNo;
    }

    /**
     * Sets the value of the requestNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestNo(BigInteger value) {
        this.requestNo = value;
    }

    /**
     * Gets the value of the insuredObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInsuredObjectID() {
        return insuredObjectID;
    }

    /**
     * Sets the value of the insuredObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInsuredObjectID(Long value) {
        this.insuredObjectID = value;
    }

    /**
     * Gets the value of the coverCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverCode() {
        return coverCode;
    }

    /**
     * Sets the value of the coverCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverCode(String value) {
        this.coverCode = value;
    }

    /**
     * Gets the value of the riskType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskType() {
        return riskType;
    }

    /**
     * Sets the value of the riskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskType(String value) {
        this.riskType = value;
    }

    /**
     * Gets the value of the inspectNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInspectNum() {
        return inspectNum;
    }

    /**
     * Sets the value of the inspectNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInspectNum(BigInteger value) {
        this.inspectNum = value;
    }

    /**
     * Gets the value of the indemnityType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndemnityType() {
        return indemnityType;
    }

    /**
     * Sets the value of the indemnityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndemnityType(BigInteger value) {
        this.indemnityType = value;
    }

    /**
     * Gets the value of the convertDateType property.
     * 
     */
    public int getConvertDateType() {
        return convertDateType;
    }

    /**
     * Sets the value of the convertDateType property.
     * 
     */
    public void setConvertDateType(int value) {
        this.convertDateType = value;
    }

    /**
     * Gets the value of the convertDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConvertDate() {
        return convertDate;
    }

    /**
     * Sets the value of the convertDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConvertDate(XMLGregorianCalendar value) {
        this.convertDate = value;
    }

    /**
     * Gets the value of the calculateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCalculateDate() {
        return calculateDate;
    }

    /**
     * Sets the value of the calculateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCalculateDate(XMLGregorianCalendar value) {
        this.calculateDate = value;
    }

    /**
     * Gets the value of the paySum property.
     * 
     */
    public double getPaySum() {
        return paySum;
    }

    /**
     * Sets the value of the paySum property.
     * 
     */
    public void setPaySum(double value) {
        this.paySum = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the calSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCalSum() {
        return calSum;
    }

    /**
     * Sets the value of the calSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCalSum(Double value) {
        this.calSum = value;
    }

    /**
     * Gets the value of the correctReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrectReason() {
        return correctReason;
    }

    /**
     * Sets the value of the correctReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrectReason(String value) {
        this.correctReason = value;
    }

    /**
     * Gets the value of the overLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverLimit() {
        return overLimit;
    }

    /**
     * Sets the value of the overLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverLimit(Integer value) {
        this.overLimit = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedOn() {
        return updatedOn;
    }

    /**
     * Sets the value of the updatedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedOn(XMLGregorianCalendar value) {
        this.updatedOn = value;
    }

    /**
     * Gets the value of the customProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CustomPropertiesType }
     *     
     */
    public CustomPropertiesType getCustomProperties() {
        return customProperties;
    }

    /**
     * Sets the value of the customProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomPropertiesType }
     *     
     */
    public void setCustomProperties(CustomPropertiesType value) {
        this.customProperties = value;
    }

    /**
     * Gets the value of the claimIndeminityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimIndeminityDetailsType }
     *     
     */
    public ClaimIndeminityDetailsType getClaimIndeminityDetails() {
        return claimIndeminityDetails;
    }

    /**
     * Sets the value of the claimIndeminityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimIndeminityDetailsType }
     *     
     */
    public void setClaimIndeminityDetails(ClaimIndeminityDetailsType value) {
        this.claimIndeminityDetails = value;
    }

}
