//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoverageAssign_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoverageAssign_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LinkedObject" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}POLICY_TYPE"/>
 *         &lt;element name="Insureds" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}LinkedInsureds_Type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoverageAssign_Type", propOrder = {
    "linkedObject",
    "insureds"
})
public class CoverageAssignType {

    @XmlElement(name = "LinkedObject")
    protected String linkedObject;
    @XmlElement(name = "Insureds")
    protected LinkedInsuredsType insureds;

    /**
     * Gets the value of the linkedObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedObject() {
        return linkedObject;
    }

    /**
     * Sets the value of the linkedObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedObject(String value) {
        this.linkedObject = value;
    }

    /**
     * Gets the value of the insureds property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedInsuredsType }
     *     
     */
    public LinkedInsuredsType getInsureds() {
        return insureds;
    }

    /**
     * Sets the value of the insureds property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedInsuredsType }
     *     
     */
    public void setInsureds(LinkedInsuredsType value) {
        this.insureds = value;
    }

}
