//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Damage_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Damage_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DamageID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DamageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DamageLevel" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WornOut" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="PartPrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="RepairWork" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MountWork" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="PaintWork" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Damage_Type", propOrder = {
    "damageID",
    "damageName",
    "damageLevel",
    "currency",
    "wornOut",
    "partPrice",
    "repairWork",
    "mountWork",
    "paintWork"
})
public class DamageType {

    @XmlElement(name = "DamageID", required = true)
    protected BigInteger damageID;
    @XmlElement(name = "DamageName", required = true)
    protected String damageName;
    @XmlElement(name = "DamageLevel", required = true)
    protected BigInteger damageLevel;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "WornOut", required = true)
    protected BigInteger wornOut;
    @XmlElement(name = "PartPrice")
    protected Double partPrice;
    @XmlElement(name = "RepairWork")
    protected Double repairWork;
    @XmlElement(name = "MountWork")
    protected Double mountWork;
    @XmlElement(name = "PaintWork")
    protected Double paintWork;

    /**
     * Gets the value of the damageID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDamageID() {
        return damageID;
    }

    /**
     * Sets the value of the damageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDamageID(BigInteger value) {
        this.damageID = value;
    }

    /**
     * Gets the value of the damageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDamageName() {
        return damageName;
    }

    /**
     * Sets the value of the damageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDamageName(String value) {
        this.damageName = value;
    }

    /**
     * Gets the value of the damageLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDamageLevel() {
        return damageLevel;
    }

    /**
     * Sets the value of the damageLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDamageLevel(BigInteger value) {
        this.damageLevel = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the wornOut property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWornOut() {
        return wornOut;
    }

    /**
     * Sets the value of the wornOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWornOut(BigInteger value) {
        this.wornOut = value;
    }

    /**
     * Gets the value of the partPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPartPrice() {
        return partPrice;
    }

    /**
     * Sets the value of the partPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPartPrice(Double value) {
        this.partPrice = value;
    }

    /**
     * Gets the value of the repairWork property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRepairWork() {
        return repairWork;
    }

    /**
     * Sets the value of the repairWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRepairWork(Double value) {
        this.repairWork = value;
    }

    /**
     * Gets the value of the mountWork property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMountWork() {
        return mountWork;
    }

    /**
     * Sets the value of the mountWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMountWork(Double value) {
        this.mountWork = value;
    }

    /**
     * Gets the value of the paintWork property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPaintWork() {
        return paintWork;
    }

    /**
     * Sets the value of the paintWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPaintWork(Double value) {
        this.paintWork = value;
    }

}
