//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Installment_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Installment_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnnexID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Currency"/>
 *         &lt;element name="CoveredFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CoveredTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DateToPay" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="AccountState" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Installment_Type", propOrder = {
    "annexID",
    "amount",
    "currency",
    "coveredFrom",
    "coveredTo",
    "dateToPay",
    "accountState",
    "accountType"
})
public class InstallmentType {

    @XmlElement(name = "AnnexID")
    protected long annexID;
    @XmlElement(name = "Amount")
    protected double amount;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "CoveredFrom", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar coveredFrom;
    @XmlElement(name = "CoveredTo")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar coveredTo;
    @XmlElement(name = "DateToPay")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateToPay;
    @XmlElement(name = "AccountState")
    protected Integer accountState;
    @XmlElement(name = "AccountType")
    protected String accountType;

    /**
     * Gets the value of the annexID property.
     * 
     */
    public long getAnnexID() {
        return annexID;
    }

    /**
     * Sets the value of the annexID property.
     * 
     */
    public void setAnnexID(long value) {
        this.annexID = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the coveredFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCoveredFrom() {
        return coveredFrom;
    }

    /**
     * Sets the value of the coveredFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCoveredFrom(XMLGregorianCalendar value) {
        this.coveredFrom = value;
    }

    /**
     * Gets the value of the coveredTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCoveredTo() {
        return coveredTo;
    }

    /**
     * Sets the value of the coveredTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCoveredTo(XMLGregorianCalendar value) {
        this.coveredTo = value;
    }

    /**
     * Gets the value of the dateToPay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateToPay() {
        return dateToPay;
    }

    /**
     * Sets the value of the dateToPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateToPay(XMLGregorianCalendar value) {
        this.dateToPay = value;
    }

    /**
     * Gets the value of the accountState property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountState() {
        return accountState;
    }

    /**
     * Sets the value of the accountState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountState(Integer value) {
        this.accountState = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

}
