//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Insured entity represents what exactly is insured
 *                               - an object (car, property, train, etc.) or a
 *                               person (for life insurance). Depending on the type
 *                               of the object, the structure may vary, which is
 *                               defined by choice between generic object
 *                               structures. Besides the predefiend fields, every
 *                               object can have a varying number of additional
 *                               fields (flex fields), which are configured at
 *                               system installation time for a certain client. The
 *                               fields are described by "any" element in the XML
 *                               structure
 * 
 * <p>Java class for InsuredEntityChange_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuredEntityChange_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ObjectType" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Owners" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}RelatedPersons" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="OAccidentInsured" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngAccidentInsured_Type"/>
 *           &lt;element name="OAdditionalEquipment" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngAdditionalEquipment_Type"/>
 *           &lt;element name="OAgriculture" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngAgriculture_Type"/>
 *           &lt;element name="OAnimal" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngAnimal_Type"/>
 *           &lt;element name="OCar" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngCar_Type"/>
 *           &lt;element name="OCargo" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngCargo_Type"/>
 *           &lt;element name="OInsuredGroups" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngInsuredGroups_Type"/>
 *           &lt;element name="OLiability" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngLiability_Type"/>
 *           &lt;element name="OLoss" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngLoss_Type"/>
 *           &lt;element name="OPlane" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngPlane_Type"/>
 *           &lt;element name="OProperty" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngProperty_Type"/>
 *           &lt;element name="OPropBri" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngPropBri_Type"/>
 *           &lt;element name="OShip" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngShip_Type"/>
 *           &lt;element name="OTrain" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChngTrain_Type"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuredEntityChange_Type", propOrder = {
    "objectID",
    "objectType",
    "owners",
    "relatedPersons",
    "oAccidentInsured",
    "oAdditionalEquipment",
    "oAgriculture",
    "oAnimal",
    "oCar",
    "oCargo",
    "oInsuredGroups",
    "oLiability",
    "oLoss",
    "oPlane",
    "oProperty",
    "oPropBri",
    "oShip",
    "oTrain"
})
public class InsuredEntityChangeType {

    @XmlElement(name = "ObjectID")
    protected BigInteger objectID;
    @XmlElement(name = "ObjectType")
    protected BigInteger objectType;
    @XmlElement(name = "Owners")
    protected OwnersType owners;
    @XmlElement(name = "RelatedPersons")
    protected RelatedPersonsType relatedPersons;
    @XmlElement(name = "OAccidentInsured")
    protected ChngAccidentInsuredType oAccidentInsured;
    @XmlElement(name = "OAdditionalEquipment")
    protected ChngAdditionalEquipmentType oAdditionalEquipment;
    @XmlElement(name = "OAgriculture")
    protected ChngAgricultureType oAgriculture;
    @XmlElement(name = "OAnimal")
    protected ChngAnimalType oAnimal;
    @XmlElement(name = "OCar")
    protected ChngCarType oCar;
    @XmlElement(name = "OCargo")
    protected ChngCargoType oCargo;
    @XmlElement(name = "OInsuredGroups")
    protected ChngInsuredGroupsType oInsuredGroups;
    @XmlElement(name = "OLiability")
    protected ChngLiabilityType oLiability;
    @XmlElement(name = "OLoss")
    protected ChngLossType oLoss;
    @XmlElement(name = "OPlane")
    protected ChngPlaneType oPlane;
    @XmlElement(name = "OProperty")
    protected ChngPropertyType oProperty;
    @XmlElement(name = "OPropBri")
    protected ChngPropBriType oPropBri;
    @XmlElement(name = "OShip")
    protected ChngShipType oShip;
    @XmlElement(name = "OTrain")
    protected ChngTrainType oTrain;

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectID(BigInteger value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectType(BigInteger value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the owners property.
     * 
     * @return
     *     possible object is
     *     {@link OwnersType }
     *     
     */
    public OwnersType getOwners() {
        return owners;
    }

    /**
     * Sets the value of the owners property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnersType }
     *     
     */
    public void setOwners(OwnersType value) {
        this.owners = value;
    }

    /**
     * Gets the value of the relatedPersons property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedPersonsType }
     *     
     */
    public RelatedPersonsType getRelatedPersons() {
        return relatedPersons;
    }

    /**
     * Sets the value of the relatedPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedPersonsType }
     *     
     */
    public void setRelatedPersons(RelatedPersonsType value) {
        this.relatedPersons = value;
    }

    /**
     * Gets the value of the oAccidentInsured property.
     * 
     * @return
     *     possible object is
     *     {@link ChngAccidentInsuredType }
     *     
     */
    public ChngAccidentInsuredType getOAccidentInsured() {
        return oAccidentInsured;
    }

    /**
     * Sets the value of the oAccidentInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngAccidentInsuredType }
     *     
     */
    public void setOAccidentInsured(ChngAccidentInsuredType value) {
        this.oAccidentInsured = value;
    }

    /**
     * Gets the value of the oAdditionalEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link ChngAdditionalEquipmentType }
     *     
     */
    public ChngAdditionalEquipmentType getOAdditionalEquipment() {
        return oAdditionalEquipment;
    }

    /**
     * Sets the value of the oAdditionalEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngAdditionalEquipmentType }
     *     
     */
    public void setOAdditionalEquipment(ChngAdditionalEquipmentType value) {
        this.oAdditionalEquipment = value;
    }

    /**
     * Gets the value of the oAgriculture property.
     * 
     * @return
     *     possible object is
     *     {@link ChngAgricultureType }
     *     
     */
    public ChngAgricultureType getOAgriculture() {
        return oAgriculture;
    }

    /**
     * Sets the value of the oAgriculture property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngAgricultureType }
     *     
     */
    public void setOAgriculture(ChngAgricultureType value) {
        this.oAgriculture = value;
    }

    /**
     * Gets the value of the oAnimal property.
     * 
     * @return
     *     possible object is
     *     {@link ChngAnimalType }
     *     
     */
    public ChngAnimalType getOAnimal() {
        return oAnimal;
    }

    /**
     * Sets the value of the oAnimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngAnimalType }
     *     
     */
    public void setOAnimal(ChngAnimalType value) {
        this.oAnimal = value;
    }

    /**
     * Gets the value of the oCar property.
     * 
     * @return
     *     possible object is
     *     {@link ChngCarType }
     *     
     */
    public ChngCarType getOCar() {
        return oCar;
    }

    /**
     * Sets the value of the oCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngCarType }
     *     
     */
    public void setOCar(ChngCarType value) {
        this.oCar = value;
    }

    /**
     * Gets the value of the oCargo property.
     * 
     * @return
     *     possible object is
     *     {@link ChngCargoType }
     *     
     */
    public ChngCargoType getOCargo() {
        return oCargo;
    }

    /**
     * Sets the value of the oCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngCargoType }
     *     
     */
    public void setOCargo(ChngCargoType value) {
        this.oCargo = value;
    }

    /**
     * Gets the value of the oInsuredGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ChngInsuredGroupsType }
     *     
     */
    public ChngInsuredGroupsType getOInsuredGroups() {
        return oInsuredGroups;
    }

    /**
     * Sets the value of the oInsuredGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngInsuredGroupsType }
     *     
     */
    public void setOInsuredGroups(ChngInsuredGroupsType value) {
        this.oInsuredGroups = value;
    }

    /**
     * Gets the value of the oLiability property.
     * 
     * @return
     *     possible object is
     *     {@link ChngLiabilityType }
     *     
     */
    public ChngLiabilityType getOLiability() {
        return oLiability;
    }

    /**
     * Sets the value of the oLiability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngLiabilityType }
     *     
     */
    public void setOLiability(ChngLiabilityType value) {
        this.oLiability = value;
    }

    /**
     * Gets the value of the oLoss property.
     * 
     * @return
     *     possible object is
     *     {@link ChngLossType }
     *     
     */
    public ChngLossType getOLoss() {
        return oLoss;
    }

    /**
     * Sets the value of the oLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngLossType }
     *     
     */
    public void setOLoss(ChngLossType value) {
        this.oLoss = value;
    }

    /**
     * Gets the value of the oPlane property.
     * 
     * @return
     *     possible object is
     *     {@link ChngPlaneType }
     *     
     */
    public ChngPlaneType getOPlane() {
        return oPlane;
    }

    /**
     * Sets the value of the oPlane property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngPlaneType }
     *     
     */
    public void setOPlane(ChngPlaneType value) {
        this.oPlane = value;
    }

    /**
     * Gets the value of the oProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ChngPropertyType }
     *     
     */
    public ChngPropertyType getOProperty() {
        return oProperty;
    }

    /**
     * Sets the value of the oProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngPropertyType }
     *     
     */
    public void setOProperty(ChngPropertyType value) {
        this.oProperty = value;
    }

    /**
     * Gets the value of the oPropBri property.
     * 
     * @return
     *     possible object is
     *     {@link ChngPropBriType }
     *     
     */
    public ChngPropBriType getOPropBri() {
        return oPropBri;
    }

    /**
     * Sets the value of the oPropBri property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngPropBriType }
     *     
     */
    public void setOPropBri(ChngPropBriType value) {
        this.oPropBri = value;
    }

    /**
     * Gets the value of the oShip property.
     * 
     * @return
     *     possible object is
     *     {@link ChngShipType }
     *     
     */
    public ChngShipType getOShip() {
        return oShip;
    }

    /**
     * Sets the value of the oShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngShipType }
     *     
     */
    public void setOShip(ChngShipType value) {
        this.oShip = value;
    }

    /**
     * Gets the value of the oTrain property.
     * 
     * @return
     *     possible object is
     *     {@link ChngTrainType }
     *     
     */
    public ChngTrainType getOTrain() {
        return oTrain;
    }

    /**
     * Sets the value of the oTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngTrainType }
     *     
     */
    public void setOTrain(ChngTrainType value) {
        this.oTrain = value;
    }

}
