//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvestmentAccount_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvestmentAccount_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}InsuredObjectID"/>
 *         &lt;element name="Covers" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}InvCovers_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvestmentAccount_Type", propOrder = {
    "insuredObjectID",
    "covers"
})
public class InvestmentAccountType {

    @XmlElement(name = "InsuredObjectID")
    protected long insuredObjectID;
    @XmlElement(name = "Covers", required = true)
    protected InvCoversType covers;

    /**
     * Gets the value of the insuredObjectID property.
     * 
     */
    public long getInsuredObjectID() {
        return insuredObjectID;
    }

    /**
     * Sets the value of the insuredObjectID property.
     * 
     */
    public void setInsuredObjectID(long value) {
        this.insuredObjectID = value;
    }

    /**
     * Gets the value of the covers property.
     * 
     * @return
     *     possible object is
     *     {@link InvCoversType }
     *     
     */
    public InvCoversType getCovers() {
        return covers;
    }

    /**
     * Sets the value of the covers property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvCoversType }
     *     
     */
    public void setCovers(InvCoversType value) {
        this.covers = value;
    }

}
