//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Insured entity represents what exactly is insured
 *                               - an object (car, property, train, etc.) or a
 *                               person (for life insurance). Depending on the type
 *                               of the object, the structure may vary, which is
 *                               defined by choice between generic object
 *                               structures. Besides the predefiend fields, every
 *                               object can have a varying number of additional
 *                               fields (flex fields), which are configured at
 *                               system installation time for a certain client. The
 *                               fields are described by "any" element in the XML
 *                               structure
 * 
 * <p>Java class for ObjectData_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectData_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ObjectType"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Owners" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OAccidentInsured"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OAdditionalEquipment"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OAgriculture"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OAnimal"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OCar"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OCargo"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OInsuredGroups"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OLiability"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OLoss"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OPlane"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OProperty"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OPropBri"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OShip"/>
 *           &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}OTrain"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectData_Type", propOrder = {
    "objectID",
    "objectType",
    "owners",
    "oAccidentInsured",
    "oAdditionalEquipment",
    "oAgriculture",
    "oAnimal",
    "oCar",
    "oCargo",
    "oInsuredGroups",
    "oLiability",
    "oLoss",
    "oPlane",
    "oProperty",
    "oPropBri",
    "oShip",
    "oTrain"
})
public class ObjectDataType {

    @XmlElement(name = "ObjectID")
    protected BigInteger objectID;
    @XmlElement(name = "ObjectType", required = true)
    protected BigInteger objectType;
    @XmlElement(name = "Owners")
    protected OwnersType owners;
    @XmlElement(name = "OAccidentInsured")
    protected OAccidentInsuredType oAccidentInsured;
    @XmlElement(name = "OAdditionalEquipment")
    protected OAdditionalEquipmentType oAdditionalEquipment;
    @XmlElement(name = "OAgriculture")
    protected OAgricultureType oAgriculture;
    @XmlElement(name = "OAnimal")
    protected OAnimalType oAnimal;
    @XmlElement(name = "OCar")
    protected OCarType oCar;
    @XmlElement(name = "OCargo")
    protected OCargoType oCargo;
    @XmlElement(name = "OInsuredGroups")
    protected OInsuredGroupsType oInsuredGroups;
    @XmlElement(name = "OLiability")
    protected OLiabilityType oLiability;
    @XmlElement(name = "OLoss")
    protected OLossType oLoss;
    @XmlElement(name = "OPlane")
    protected OPlaneType oPlane;
    @XmlElement(name = "OProperty")
    protected OPropertyType oProperty;
    @XmlElement(name = "OPropBri")
    protected OPropBriType oPropBri;
    @XmlElement(name = "OShip")
    protected OShipType oShip;
    @XmlElement(name = "OTrain")
    protected OTrainType oTrain;

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectID(BigInteger value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectType(BigInteger value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the owners property.
     * 
     * @return
     *     possible object is
     *     {@link OwnersType }
     *     
     */
    public OwnersType getOwners() {
        return owners;
    }

    /**
     * Sets the value of the owners property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnersType }
     *     
     */
    public void setOwners(OwnersType value) {
        this.owners = value;
    }

    /**
     * Insured for an accident. Describes
     *                                           insureds by an individual. The
     *                                           predefined fields are: - PersonID: ID
     *                                           for person in p_people table; - Age:
     *                                           age of the person - ProfID: profession
     *                                           ID from the list of professions
     * 
     * @return
     *     possible object is
     *     {@link OAccidentInsuredType }
     *     
     */
    public OAccidentInsuredType getOAccidentInsured() {
        return oAccidentInsured;
    }

    /**
     * Sets the value of the oAccidentInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link OAccidentInsuredType }
     *     
     */
    public void setOAccidentInsured(OAccidentInsuredType value) {
        this.oAccidentInsured = value;
    }

    /**
     * Additional equipment of various
     *                                           vehicles. Mainly for cars. -
     *                                           ParentObjectID: Vehicle code; -
     *                                           EquipmentType: Equipment type code -
     *                                           Model: Equipment model - SerialNo -
     *                                           IVOver: Flag. Shows if the insured
     *                                           value should be accumulated; -
     *                                           AvValue: Average value; - EquipmentKind
     * 
     * @return
     *     possible object is
     *     {@link OAdditionalEquipmentType }
     *     
     */
    public OAdditionalEquipmentType getOAdditionalEquipment() {
        return oAdditionalEquipment;
    }

    /**
     * Sets the value of the oAdditionalEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OAdditionalEquipmentType }
     *     
     */
    public void setOAdditionalEquipment(OAdditionalEquipmentType value) {
        this.oAdditionalEquipment = value;
    }

    /**
     * Data about the insured cultivations. -
     *                                           CultureType: Cultivation type; -
     *                                           CultureSubtype: Subcultivation type; -
     *                                           Area: The area, sowed by the
     *                                           cultivation(dka); - RegioID: The code
     *                                           of the area, sowed by the cultivation;
     *                                           - CadastNum: The number of the area in
     *                                           the public registries, sowed by the
     *                                           cultivation
     * 
     * @return
     *     possible object is
     *     {@link OAgricultureType }
     *     
     */
    public OAgricultureType getOAgriculture() {
        return oAgriculture;
    }

    /**
     * Sets the value of the oAgriculture property.
     * 
     * @param value
     *     allowed object is
     *     {@link OAgricultureType }
     *     
     */
    public void setOAgriculture(OAgricultureType value) {
        this.oAgriculture = value;
    }

    /**
     * Information about the insured animals.
     *                                           - AnimalType: Animal type in
     *                                           accordance of the internal
     *                                           nomenclature; - AnimalSubtype:Animal
     *                                           subtype in accordance of the internal
     *                                           nomenclature; - Breed: Animal breed -
     *                                           Name - Distinction:Distinguishing
     *                                           feachers
     * 
     * @return
     *     possible object is
     *     {@link OAnimalType }
     *     
     */
    public OAnimalType getOAnimal() {
        return oAnimal;
    }

    /**
     * Sets the value of the oAnimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link OAnimalType }
     *     
     */
    public void setOAnimal(OAnimalType value) {
        this.oAnimal = value;
    }

    /**
     * Contains the data about cars with
     *                                           motorcar place accident insurance. -
     *                                           RegNo:THE REGISTRATION NUMBER OF THE
     *                                           VEHICLE; - CarType: A car type in
     *                                           accordance of the internal
     *                                           nomenclature; - Model: Car model; -
     *                                           Make: Car maker; - Modification -
     *                                           Chassis: Chassis number - Engine:
     *                                           Engine number - CCMTon: Engine
     *                                           power(weight-TON); - CarUsage: Car
     *                                           usage-in accordance of the internal
     *                                           nomenclature; - SeatsNum: Number of
     *                                           seats; - DoorNum: Number of doors; -
     *                                           PaintType: Paint type-common or
     *                                           metalic; - ProdYear: Year of
     *                                           production; - CarAge: Age; - ProdType:
     *                                           Production type-Eastern or Western ; -
     *                                           CarColo - RegType - EnginePower -
     *                                           BonusMalus - Tonage - EngineType -
     *                                           FuelType - DriveType - CarBodyType -
     *                                           WindowColor - Modified - Notes
     * 
     * @return
     *     possible object is
     *     {@link OCarType }
     *     
     */
    public OCarType getOCar() {
        return oCar;
    }

    /**
     * Sets the value of the oCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link OCarType }
     *     
     */
    public void setOCar(OCarType value) {
        this.oCar = value;
    }

    /**
     * Description of the insured goods in
     *                                           the subscription policies. -
     *                                           CargoType: Goods type in accordance
     *                                           with a internal nomenclature; -
     *                                           CargoSubtype - CargoPolicyType -
     *                                           Description - PackingType: Package
     *                                           type in accordance with a internal
     *                                           nomenclature; - BoxNumber: Number of
     *                                           the packages; - TeritoryID: Teritory
     *                                           ID in accordance with a internal
     *                                           nomenclature; - FromPlace: The start
     *                                           place of the route; - ToPlace: The end
     *                                           place of the route; - Via: The place,
     *                                           via which is the route; - Destination:
     *                                           Final destination; - TransportType -
     *                                           VehicleType - FreightPrc: Freight(% to
     *                                           get more expensive as a result of
     *                                           transportation); - FreightDim -
     *                                           ShipmentDoc: Shipment document; -
     *                                           ToOrder - AverageAgent - Distance
     * 
     * @return
     *     possible object is
     *     {@link OCargoType }
     *     
     */
    public OCargoType getOCargo() {
        return oCargo;
    }

    /**
     * Sets the value of the oCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OCargoType }
     *     
     */
    public void setOCargo(OCargoType value) {
        this.oCargo = value;
    }

    /**
     * Group Insurance
     * 
     * @return
     *     possible object is
     *     {@link OInsuredGroupsType }
     *     
     */
    public OInsuredGroupsType getOInsuredGroups() {
        return oInsuredGroups;
    }

    /**
     * Sets the value of the oInsuredGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link OInsuredGroupsType }
     *     
     */
    public void setOInsuredGroups(OInsuredGroupsType value) {
        this.oInsuredGroups = value;
    }

    /**
     * General purpose object. Mainly used
     *                                           for liability insurance. - LiabDesc:
     *                                           Liability description; - LiabType:
     *                                           Liability type; - AddressID
     * 
     * @return
     *     possible object is
     *     {@link OLiabilityType }
     *     
     */
    public OLiabilityType getOLiability() {
        return oLiability;
    }

    /**
     * Sets the value of the oLiability property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLiabilityType }
     *     
     */
    public void setOLiability(OLiabilityType value) {
        this.oLiability = value;
    }

    /**
     * Claim inventory. Contains description
     *                                           of losses when claim
     * 
     * @return
     *     possible object is
     *     {@link OLossType }
     *     
     */
    public OLossType getOLoss() {
        return oLoss;
    }

    /**
     * Sets the value of the oLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLossType }
     *     
     */
    public void setOLoss(OLossType value) {
        this.oLoss = value;
    }

    /**
     * Planes. - Make: Plain maker; - RegNo:
     *                                           Registration number; - ProdNo: Number
     *                                           given by the producer - ProdYear: Year
     *                                           of production - CCMTon: Tonage -
     *                                           SeatsNum: Number of seats -
     *                                           PlainHistory: Free text for plane
     *                                           history
     * 
     * @return
     *     possible object is
     *     {@link OPlaneType }
     *     
     */
    public OPlaneType getOPlane() {
        return oPlane;
    }

    /**
     * Sets the value of the oPlane property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPlaneType }
     *     
     */
    public void setOPlane(OPlaneType value) {
        this.oPlane = value;
    }

    /**
     * Insured property. - PropertyKind; -
     *                                           PropertyType: Property
     *                                           type(estate/movable) - Name: Name
     *                                           (property description) - AddressID: ID
     *                                           of address structure
     * 
     * @return
     *     possible object is
     *     {@link OPropertyType }
     *     
     */
    public OPropertyType getOProperty() {
        return oProperty;
    }

    /**
     * Sets the value of the oProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPropertyType }
     *     
     */
    public void setOProperty(OPropertyType value) {
        this.oProperty = value;
    }

    /**
     * Insured building. Contains data about
     *                                           Insured building, typically building
     *                                           in construction. - Construction; -
     *                                           Area: area in square meters; -
     *                                           AddressID: ID of address structure; -
     *                                           BriDescription: The description of the
     *                                           insured object
     * 
     * @return
     *     possible object is
     *     {@link OPropBriType }
     *     
     */
    public OPropBriType getOPropBri() {
        return oPropBri;
    }

    /**
     * Sets the value of the oPropBri property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPropBriType }
     *     
     */
    public void setOPropBri(OPropBriType value) {
        this.oPropBri = value;
    }

    /**
     * Ships. - Name; - ShipClass ; -
     *                                           ShipType; - RegNo: Registration
     *                                           number; - RegPort: Port of
     *                                           registration; - GrossTonage: Gross
     *                                           register ton; - NetTonage: Net
     *                                           register ton; - OwnerClass; - Length;
     *                                           - Height; - Wide; - Wade; -
     *                                           DeadWeight; - Region: Insured region;
     *                                           - PreviousInsurer; - PassengerNum; -
     *                                           CrewNum; - LastMaintenanceDate; -
     *                                           Engine: Engine info; - ProdInfo:
     *                                           Production info; - ProdYear: Year of
     *                                           production; - Producer; - ClaimInfo:
     *                                           Previous claim info.
     * 
     * @return
     *     possible object is
     *     {@link OShipType }
     *     
     */
    public OShipType getOShip() {
        return oShip;
    }

    /**
     * Sets the value of the oShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link OShipType }
     *     
     */
    public void setOShip(OShipType value) {
        this.oShip = value;
    }

    /**
     * Trains.
     * 
     * @return
     *     possible object is
     *     {@link OTrainType }
     *     
     */
    public OTrainType getOTrain() {
        return oTrain;
    }

    /**
     * Sets the value of the oTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTrainType }
     *     
     */
    public void setOTrain(OTrainType value) {
        this.oTrain = value;
    }

}
