//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OVechicle_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OVechicle_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ObjectType"/>
 *         &lt;element name="VehicleObjectID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="VehicleDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BoxNum" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FromPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ToPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TeritoryID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Param1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Param2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Param3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Param4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Param5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OVechicle_Type", propOrder = {
    "objectType",
    "vehicleObjectID",
    "vehicleDescription",
    "boxNum",
    "fromPlace",
    "toPlace",
    "teritoryID",
    "param1",
    "param2",
    "param3",
    "param4",
    "param5"
})
public class OVechicleType {

    @XmlElement(name = "ObjectType", required = true)
    protected BigInteger objectType;
    @XmlElement(name = "VehicleObjectID")
    protected long vehicleObjectID;
    @XmlElement(name = "VehicleDescription")
    protected String vehicleDescription;
    @XmlElement(name = "BoxNum")
    protected BigInteger boxNum;
    @XmlElement(name = "FromPlace")
    protected String fromPlace;
    @XmlElement(name = "ToPlace")
    protected String toPlace;
    @XmlElement(name = "TeritoryID")
    protected String teritoryID;
    @XmlElement(name = "Param1")
    protected String param1;
    @XmlElement(name = "Param2")
    protected String param2;
    @XmlElement(name = "Param3")
    protected String param3;
    @XmlElement(name = "Param4")
    protected String param4;
    @XmlElement(name = "Param5")
    protected String param5;

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectType(BigInteger value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the vehicleObjectID property.
     * 
     */
    public long getVehicleObjectID() {
        return vehicleObjectID;
    }

    /**
     * Sets the value of the vehicleObjectID property.
     * 
     */
    public void setVehicleObjectID(long value) {
        this.vehicleObjectID = value;
    }

    /**
     * Gets the value of the vehicleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleDescription() {
        return vehicleDescription;
    }

    /**
     * Sets the value of the vehicleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleDescription(String value) {
        this.vehicleDescription = value;
    }

    /**
     * Gets the value of the boxNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBoxNum() {
        return boxNum;
    }

    /**
     * Sets the value of the boxNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBoxNum(BigInteger value) {
        this.boxNum = value;
    }

    /**
     * Gets the value of the fromPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromPlace() {
        return fromPlace;
    }

    /**
     * Sets the value of the fromPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromPlace(String value) {
        this.fromPlace = value;
    }

    /**
     * Gets the value of the toPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToPlace() {
        return toPlace;
    }

    /**
     * Sets the value of the toPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToPlace(String value) {
        this.toPlace = value;
    }

    /**
     * Gets the value of the teritoryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeritoryID() {
        return teritoryID;
    }

    /**
     * Sets the value of the teritoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeritoryID(String value) {
        this.teritoryID = value;
    }

    /**
     * Gets the value of the param1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam1() {
        return param1;
    }

    /**
     * Sets the value of the param1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam1(String value) {
        this.param1 = value;
    }

    /**
     * Gets the value of the param2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam2() {
        return param2;
    }

    /**
     * Sets the value of the param2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam2(String value) {
        this.param2 = value;
    }

    /**
     * Gets the value of the param3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam3() {
        return param3;
    }

    /**
     * Sets the value of the param3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam3(String value) {
        this.param3 = value;
    }

    /**
     * Gets the value of the param4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam4() {
        return param4;
    }

    /**
     * Sets the value of the param4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam4(String value) {
        this.param4 = value;
    }

    /**
     * Gets the value of the param5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam5() {
        return param5;
    }

    /**
     * Sets the value of the param5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam5(String value) {
        this.param5 = value;
    }

}
