//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PolicyParReq_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyParReq_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolParID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}SrvgrpID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}SrvgrpCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}SrvgrpName" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ServiceID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ServiceCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ServiceName" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DiagnosisID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DiagnosisCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DiagnosisName" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DiagnosisGroupID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DiagnosisGroupCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DiagnosisGroupName" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DrugID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DrugCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DrugName" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DrugGroupID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DrugGroupCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}DrugGroupName" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="DrugDaySupply" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}GeogAreaCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}GeogAreaName" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ProviderID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ProviderCode"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}NetworkID" minOccurs="0"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}NetworkCode"/>
 *             &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}NetworkName" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ProviderType" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ServicePlace" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}CoverageType" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ClaimType" minOccurs="0"/>
 *         &lt;element name="SettlementType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}NetworkCoverage" minOccurs="0"/>
 *         &lt;element name="ParLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Currency" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}CoverCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}InsuredObjectID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}GroupID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}AnnexID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}AuxAnnexID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}InsrBegin" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}InsrEnd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyParReq_Type", propOrder = {
    "polParID",
    "srvgrpID",
    "srvgrpCode",
    "srvgrpName",
    "serviceID",
    "serviceCode",
    "serviceName",
    "diagnosisID",
    "diagnosisCode",
    "diagnosisName",
    "diagnosisGroupID",
    "diagnosisGroupCode",
    "diagnosisGroupName",
    "drugID",
    "drugCode",
    "drugName",
    "drugGroupID",
    "drugGroupCode",
    "drugGroupName",
    "drugDaySupply",
    "geogAreaCode",
    "geogAreaName",
    "providerID",
    "providerCode",
    "networkID",
    "networkCode",
    "networkName",
    "providerType",
    "servicePlace",
    "coverageType",
    "claimType",
    "settlementType",
    "networkCoverage",
    "parLimit",
    "currency",
    "coverCode",
    "insuredObjectID",
    "groupID",
    "annexID",
    "auxAnnexID",
    "insrBegin",
    "insrEnd"
})
public class PolicyParReqType {

    @XmlElement(name = "PolParID")
    protected Long polParID;
    @XmlElement(name = "SrvgrpID")
    protected Long srvgrpID;
    @XmlElement(name = "SrvgrpCode")
    protected String srvgrpCode;
    @XmlElement(name = "SrvgrpName")
    protected String srvgrpName;
    @XmlElement(name = "ServiceID")
    protected Long serviceID;
    @XmlElement(name = "ServiceCode")
    protected String serviceCode;
    @XmlElement(name = "ServiceName")
    protected String serviceName;
    @XmlElement(name = "DiagnosisID")
    protected Long diagnosisID;
    @XmlElement(name = "DiagnosisCode")
    protected String diagnosisCode;
    @XmlElement(name = "DiagnosisName")
    protected String diagnosisName;
    @XmlElement(name = "DiagnosisGroupID")
    protected Long diagnosisGroupID;
    @XmlElement(name = "DiagnosisGroupCode")
    protected String diagnosisGroupCode;
    @XmlElement(name = "DiagnosisGroupName")
    protected String diagnosisGroupName;
    @XmlElement(name = "DrugID")
    protected Long drugID;
    @XmlElement(name = "DrugCode")
    protected String drugCode;
    @XmlElement(name = "DrugName")
    protected String drugName;
    @XmlElement(name = "DrugGroupID")
    protected Long drugGroupID;
    @XmlElement(name = "DrugGroupCode")
    protected String drugGroupCode;
    @XmlElement(name = "DrugGroupName")
    protected String drugGroupName;
    @XmlElement(name = "DrugDaySupply")
    protected BigInteger drugDaySupply;
    @XmlElement(name = "GeogAreaCode")
    protected String geogAreaCode;
    @XmlElement(name = "GeogAreaName")
    protected String geogAreaName;
    @XmlElement(name = "ProviderID")
    protected Long providerID;
    @XmlElement(name = "ProviderCode")
    protected String providerCode;
    @XmlElement(name = "NetworkID")
    protected Long networkID;
    @XmlElement(name = "NetworkCode")
    protected String networkCode;
    @XmlElement(name = "NetworkName")
    protected String networkName;
    @XmlElement(name = "ProviderType")
    protected String providerType;
    @XmlElement(name = "ServicePlace")
    protected String servicePlace;
    @XmlElement(name = "CoverageType")
    protected String coverageType;
    @XmlElement(name = "ClaimType")
    protected String claimType;
    @XmlElement(name = "SettlementType")
    protected String settlementType;
    @XmlElement(name = "NetworkCoverage")
    protected String networkCoverage;
    @XmlElement(name = "ParLimit")
    protected BigDecimal parLimit;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "CoverCode")
    protected String coverCode;
    @XmlElement(name = "InsuredObjectID")
    protected Long insuredObjectID;
    @XmlElement(name = "GroupID")
    protected Long groupID;
    @XmlElement(name = "AnnexID")
    protected BigInteger annexID;
    @XmlElement(name = "AuxAnnexID")
    protected BigInteger auxAnnexID;
    @XmlElement(name = "InsrBegin")
    protected String insrBegin;
    @XmlElement(name = "InsrEnd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar insrEnd;

    /**
     * Gets the value of the polParID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPolParID() {
        return polParID;
    }

    /**
     * Sets the value of the polParID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPolParID(Long value) {
        this.polParID = value;
    }

    /**
     * Gets the value of the srvgrpID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSrvgrpID() {
        return srvgrpID;
    }

    /**
     * Sets the value of the srvgrpID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSrvgrpID(Long value) {
        this.srvgrpID = value;
    }

    /**
     * Gets the value of the srvgrpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvgrpCode() {
        return srvgrpCode;
    }

    /**
     * Sets the value of the srvgrpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvgrpCode(String value) {
        this.srvgrpCode = value;
    }

    /**
     * Gets the value of the srvgrpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrvgrpName() {
        return srvgrpName;
    }

    /**
     * Sets the value of the srvgrpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrvgrpName(String value) {
        this.srvgrpName = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setServiceID(Long value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the diagnosisID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDiagnosisID() {
        return diagnosisID;
    }

    /**
     * Sets the value of the diagnosisID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDiagnosisID(Long value) {
        this.diagnosisID = value;
    }

    /**
     * Gets the value of the diagnosisCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosisCode() {
        return diagnosisCode;
    }

    /**
     * Sets the value of the diagnosisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosisCode(String value) {
        this.diagnosisCode = value;
    }

    /**
     * Gets the value of the diagnosisName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosisName() {
        return diagnosisName;
    }

    /**
     * Sets the value of the diagnosisName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosisName(String value) {
        this.diagnosisName = value;
    }

    /**
     * Gets the value of the diagnosisGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDiagnosisGroupID() {
        return diagnosisGroupID;
    }

    /**
     * Sets the value of the diagnosisGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDiagnosisGroupID(Long value) {
        this.diagnosisGroupID = value;
    }

    /**
     * Gets the value of the diagnosisGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosisGroupCode() {
        return diagnosisGroupCode;
    }

    /**
     * Sets the value of the diagnosisGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosisGroupCode(String value) {
        this.diagnosisGroupCode = value;
    }

    /**
     * Gets the value of the diagnosisGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosisGroupName() {
        return diagnosisGroupName;
    }

    /**
     * Sets the value of the diagnosisGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosisGroupName(String value) {
        this.diagnosisGroupName = value;
    }

    /**
     * Gets the value of the drugID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDrugID() {
        return drugID;
    }

    /**
     * Sets the value of the drugID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDrugID(Long value) {
        this.drugID = value;
    }

    /**
     * Gets the value of the drugCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugCode() {
        return drugCode;
    }

    /**
     * Sets the value of the drugCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugCode(String value) {
        this.drugCode = value;
    }

    /**
     * Gets the value of the drugName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * Sets the value of the drugName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugName(String value) {
        this.drugName = value;
    }

    /**
     * Gets the value of the drugGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDrugGroupID() {
        return drugGroupID;
    }

    /**
     * Sets the value of the drugGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDrugGroupID(Long value) {
        this.drugGroupID = value;
    }

    /**
     * Gets the value of the drugGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugGroupCode() {
        return drugGroupCode;
    }

    /**
     * Sets the value of the drugGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugGroupCode(String value) {
        this.drugGroupCode = value;
    }

    /**
     * Gets the value of the drugGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugGroupName() {
        return drugGroupName;
    }

    /**
     * Sets the value of the drugGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugGroupName(String value) {
        this.drugGroupName = value;
    }

    /**
     * Gets the value of the drugDaySupply property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDrugDaySupply() {
        return drugDaySupply;
    }

    /**
     * Sets the value of the drugDaySupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDrugDaySupply(BigInteger value) {
        this.drugDaySupply = value;
    }

    /**
     * Gets the value of the geogAreaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeogAreaCode() {
        return geogAreaCode;
    }

    /**
     * Sets the value of the geogAreaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeogAreaCode(String value) {
        this.geogAreaCode = value;
    }

    /**
     * Gets the value of the geogAreaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeogAreaName() {
        return geogAreaName;
    }

    /**
     * Sets the value of the geogAreaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeogAreaName(String value) {
        this.geogAreaName = value;
    }

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProviderID(Long value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the providerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderCode() {
        return providerCode;
    }

    /**
     * Sets the value of the providerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderCode(String value) {
        this.providerCode = value;
    }

    /**
     * Gets the value of the networkID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNetworkID() {
        return networkID;
    }

    /**
     * Sets the value of the networkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNetworkID(Long value) {
        this.networkID = value;
    }

    /**
     * Gets the value of the networkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkCode() {
        return networkCode;
    }

    /**
     * Sets the value of the networkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkCode(String value) {
        this.networkCode = value;
    }

    /**
     * Gets the value of the networkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkName() {
        return networkName;
    }

    /**
     * Sets the value of the networkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkName(String value) {
        this.networkName = value;
    }

    /**
     * Gets the value of the providerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderType() {
        return providerType;
    }

    /**
     * Sets the value of the providerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderType(String value) {
        this.providerType = value;
    }

    /**
     * Gets the value of the servicePlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicePlace() {
        return servicePlace;
    }

    /**
     * Sets the value of the servicePlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicePlace(String value) {
        this.servicePlace = value;
    }

    /**
     * Gets the value of the coverageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverageType() {
        return coverageType;
    }

    /**
     * Sets the value of the coverageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverageType(String value) {
        this.coverageType = value;
    }

    /**
     * Gets the value of the claimType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimType() {
        return claimType;
    }

    /**
     * Sets the value of the claimType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimType(String value) {
        this.claimType = value;
    }

    /**
     * Gets the value of the settlementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementType() {
        return settlementType;
    }

    /**
     * Sets the value of the settlementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementType(String value) {
        this.settlementType = value;
    }

    /**
     * Gets the value of the networkCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkCoverage() {
        return networkCoverage;
    }

    /**
     * Sets the value of the networkCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkCoverage(String value) {
        this.networkCoverage = value;
    }

    /**
     * Gets the value of the parLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParLimit() {
        return parLimit;
    }

    /**
     * Sets the value of the parLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParLimit(BigDecimal value) {
        this.parLimit = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the coverCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverCode() {
        return coverCode;
    }

    /**
     * Sets the value of the coverCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverCode(String value) {
        this.coverCode = value;
    }

    /**
     * Gets the value of the insuredObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInsuredObjectID() {
        return insuredObjectID;
    }

    /**
     * Sets the value of the insuredObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInsuredObjectID(Long value) {
        this.insuredObjectID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGroupID(Long value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the annexID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnnexID() {
        return annexID;
    }

    /**
     * Sets the value of the annexID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnnexID(BigInteger value) {
        this.annexID = value;
    }

    /**
     * Gets the value of the auxAnnexID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAuxAnnexID() {
        return auxAnnexID;
    }

    /**
     * Sets the value of the auxAnnexID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAuxAnnexID(BigInteger value) {
        this.auxAnnexID = value;
    }

    /**
     * Gets the value of the insrBegin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsrBegin() {
        return insrBegin;
    }

    /**
     * Sets the value of the insrBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsrBegin(String value) {
        this.insrBegin = value;
    }

    /**
     * Gets the value of the insrEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsrEnd() {
        return insrEnd;
    }

    /**
     * Sets the value of the insrEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsrEnd(XMLGregorianCalendar value) {
        this.insrEnd = value;
    }

}
