//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyRuleAttr_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyRuleAttr_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}PolicyRuleID" minOccurs="0"/>
 *         &lt;element name="AttrOrder" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DefinitionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttrCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RuleValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ReRuleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValueDim" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Currency" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyRuleAttr_Type", propOrder = {
    "policyRuleID",
    "attrOrder",
    "definitionType",
    "attrCode",
    "valueType",
    "ruleValue",
    "reRuleCode",
    "valueDim",
    "currency"
})
public class PolicyRuleAttrType {

    @XmlElement(name = "PolicyRuleID")
    protected Long policyRuleID;
    @XmlElement(name = "AttrOrder")
    protected int attrOrder;
    @XmlElement(name = "DefinitionType", required = true)
    protected String definitionType;
    @XmlElement(name = "AttrCode")
    protected String attrCode;
    @XmlElement(name = "ValueType")
    protected String valueType;
    @XmlElement(name = "RuleValue")
    protected BigDecimal ruleValue;
    @XmlElement(name = "ReRuleCode")
    protected String reRuleCode;
    @XmlElement(name = "ValueDim")
    protected String valueDim;
    @XmlElement(name = "Currency")
    protected String currency;

    /**
     * Gets the value of the policyRuleID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPolicyRuleID() {
        return policyRuleID;
    }

    /**
     * Sets the value of the policyRuleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPolicyRuleID(Long value) {
        this.policyRuleID = value;
    }

    /**
     * Gets the value of the attrOrder property.
     * 
     */
    public int getAttrOrder() {
        return attrOrder;
    }

    /**
     * Sets the value of the attrOrder property.
     * 
     */
    public void setAttrOrder(int value) {
        this.attrOrder = value;
    }

    /**
     * Gets the value of the definitionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinitionType() {
        return definitionType;
    }

    /**
     * Sets the value of the definitionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinitionType(String value) {
        this.definitionType = value;
    }

    /**
     * Gets the value of the attrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * Sets the value of the attrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrCode(String value) {
        this.attrCode = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueType(String value) {
        this.valueType = value;
    }

    /**
     * Gets the value of the ruleValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRuleValue() {
        return ruleValue;
    }

    /**
     * Sets the value of the ruleValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRuleValue(BigDecimal value) {
        this.ruleValue = value;
    }

    /**
     * Gets the value of the reRuleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReRuleCode() {
        return reRuleCode;
    }

    /**
     * Sets the value of the reRuleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReRuleCode(String value) {
        this.reRuleCode = value;
    }

    /**
     * Gets the value of the valueDim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDim() {
        return valueDim;
    }

    /**
     * Sets the value of the valueDim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDim(String value) {
        this.valueDim = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
