//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Recapitulation_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Recapitulation_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecapitulationID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DocSum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ExpertSum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ConfirmSum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Recapitulation_Type", propOrder = {
    "recapitulationID",
    "docSum",
    "expertSum",
    "confirmSum"
})
public class RecapitulationType {

    @XmlElement(name = "RecapitulationID", required = true)
    protected BigInteger recapitulationID;
    @XmlElement(name = "DocSum")
    protected Double docSum;
    @XmlElement(name = "ExpertSum")
    protected Double expertSum;
    @XmlElement(name = "ConfirmSum")
    protected Double confirmSum;

    /**
     * Gets the value of the recapitulationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecapitulationID() {
        return recapitulationID;
    }

    /**
     * Sets the value of the recapitulationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecapitulationID(BigInteger value) {
        this.recapitulationID = value;
    }

    /**
     * Gets the value of the docSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDocSum() {
        return docSum;
    }

    /**
     * Sets the value of the docSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDocSum(Double value) {
        this.docSum = value;
    }

    /**
     * Gets the value of the expertSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getExpertSum() {
        return expertSum;
    }

    /**
     * Sets the value of the expertSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setExpertSum(Double value) {
        this.expertSum = value;
    }

    /**
     * Gets the value of the confirmSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConfirmSum() {
        return confirmSum;
    }

    /**
     * Sets the value of the confirmSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConfirmSum(Double value) {
        this.confirmSum = value;
    }

}
