//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedPerson_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedPerson_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="PersonID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *           &lt;element name="OthersData" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ChangeOthersData_Type"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}PID"/>
 *         &lt;element name="PersonType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}PolicyID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}AnnexID" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}ProductCode" minOccurs="0"/>
 *         &lt;element name="IncludedPolicy" type="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}BOOLEAN_STRING_TYPE" minOccurs="0"/>
 *         &lt;group ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}Change_People_Data_Group"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedPerson_Type", propOrder = {
    "personID",
    "othersData",
    "pid",
    "personType",
    "note",
    "policyID",
    "annexID",
    "productCode",
    "includedPolicy",
    "entity",
    "addresses",
    "contacts",
    "bankAccounts",
    "creditCards"
})
public class RelatedPersonType {

    @XmlElement(name = "PersonID")
    protected BigInteger personID;
    @XmlElement(name = "OthersData")
    protected ChangeOthersDataType othersData;
    @XmlElement(name = "PID", required = true)
    protected String pid;
    @XmlElement(name = "PersonType", required = true)
    protected BigInteger personType;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "PolicyID")
    protected Long policyID;
    @XmlElement(name = "AnnexID")
    protected BigInteger annexID;
    @XmlElement(name = "ProductCode")
    protected String productCode;
    @XmlElement(name = "IncludedPolicy")
    protected String includedPolicy;
    @XmlElement(name = "Entity", required = true)
    protected ChngeEntityDataType entity;
    @XmlElement(name = "Addresses")
    protected ChngeAddressesType addresses;
    @XmlElement(name = "Contacts")
    protected ChngeContactsType contacts;
    @XmlElement(name = "BankAccounts")
    protected ChngeBankAccntsType bankAccounts;
    @XmlElement(name = "CreditCards")
    protected ChngeCreditCardsType creditCards;

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersonID(BigInteger value) {
        this.personID = value;
    }

    /**
     * Gets the value of the othersData property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeOthersDataType }
     *     
     */
    public ChangeOthersDataType getOthersData() {
        return othersData;
    }

    /**
     * Sets the value of the othersData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeOthersDataType }
     *     
     */
    public void setOthersData(ChangeOthersDataType value) {
        this.othersData = value;
    }

    /**
     * Gets the value of the pid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPID() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPID(String value) {
        this.pid = value;
    }

    /**
     * Gets the value of the personType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersonType() {
        return personType;
    }

    /**
     * Sets the value of the personType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersonType(BigInteger value) {
        this.personType = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the policyID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPolicyID() {
        return policyID;
    }

    /**
     * Sets the value of the policyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPolicyID(Long value) {
        this.policyID = value;
    }

    /**
     * Gets the value of the annexID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnnexID() {
        return annexID;
    }

    /**
     * Sets the value of the annexID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnnexID(BigInteger value) {
        this.annexID = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the includedPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludedPolicy() {
        return includedPolicy;
    }

    /**
     * Sets the value of the includedPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludedPolicy(String value) {
        this.includedPolicy = value;
    }

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link ChngeEntityDataType }
     *     
     */
    public ChngeEntityDataType getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngeEntityDataType }
     *     
     */
    public void setEntity(ChngeEntityDataType value) {
        this.entity = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link ChngeAddressesType }
     *     
     */
    public ChngeAddressesType getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngeAddressesType }
     *     
     */
    public void setAddresses(ChngeAddressesType value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * @return
     *     possible object is
     *     {@link ChngeContactsType }
     *     
     */
    public ChngeContactsType getContacts() {
        return contacts;
    }

    /**
     * Sets the value of the contacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngeContactsType }
     *     
     */
    public void setContacts(ChngeContactsType value) {
        this.contacts = value;
    }

    /**
     * Gets the value of the bankAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link ChngeBankAccntsType }
     *     
     */
    public ChngeBankAccntsType getBankAccounts() {
        return bankAccounts;
    }

    /**
     * Sets the value of the bankAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngeBankAccntsType }
     *     
     */
    public void setBankAccounts(ChngeBankAccntsType value) {
        this.bankAccounts = value;
    }

    /**
     * Gets the value of the creditCards property.
     * 
     * @return
     *     possible object is
     *     {@link ChngeCreditCardsType }
     *     
     */
    public ChngeCreditCardsType getCreditCards() {
        return creditCards;
    }

    /**
     * Sets the value of the creditCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngeCreditCardsType }
     *     
     */
    public void setCreditCards(ChngeCreditCardsType value) {
        this.creditCards = value;
    }

}
