//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WfAttachmentPackage_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WfAttachmentPackage_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttachmentType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReferenceID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ConfidentialLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.fadata.bg/Insurance_Messages/v3.0/xml/}AttachmentFiles"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WfAttachmentPackage_Type", propOrder = {
    "attachmentType",
    "description",
    "referenceType",
    "referenceID",
    "confidentialLevel",
    "attachmentFiles"
})
public class WfAttachmentPackageType {

    @XmlElement(name = "AttachmentType")
    protected int attachmentType;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "ReferenceType", required = true)
    protected String referenceType;
    @XmlElement(name = "ReferenceID")
    protected Long referenceID;
    @XmlElement(name = "ConfidentialLevel")
    protected String confidentialLevel;
    @XmlElement(name = "AttachmentFiles", required = true)
    protected AttachmentFilesType attachmentFiles;

    /**
     * Gets the value of the attachmentType property.
     * 
     */
    public int getAttachmentType() {
        return attachmentType;
    }

    /**
     * Sets the value of the attachmentType property.
     * 
     */
    public void setAttachmentType(int value) {
        this.attachmentType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the referenceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * Sets the value of the referenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceType(String value) {
        this.referenceType = value;
    }

    /**
     * Gets the value of the referenceID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReferenceID() {
        return referenceID;
    }

    /**
     * Sets the value of the referenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReferenceID(Long value) {
        this.referenceID = value;
    }

    /**
     * Gets the value of the confidentialLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialLevel() {
        return confidentialLevel;
    }

    /**
     * Sets the value of the confidentialLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialLevel(String value) {
        this.confidentialLevel = value;
    }

    /**
     * Gets the value of the attachmentFiles property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentFilesType }
     *     
     */
    public AttachmentFilesType getAttachmentFiles() {
        return attachmentFiles;
    }

    /**
     * Sets the value of the attachmentFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentFilesType }
     *     
     */
    public void setAttachmentFiles(AttachmentFilesType value) {
        this.attachmentFiles = value;
    }

}
