//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.28 at 08:49:50 AM WEST 
//


package bg.fadata.insurance_messages.v3_0.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WfStep_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WfStep_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WfStepID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ProcessID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ProcessCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StepCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrentState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PrevWfStepID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="CreateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="StartedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ExecutedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExecutionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Term1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Duration1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Duration2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MainTerm" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MainDuration" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="CopyWfStepID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="SubWfStepID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="CanceledBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CancelTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="CancelReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ObjectKind" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObjectKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActivityCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Parameters" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartEndFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrgunitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Term2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Timout" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="WfStage1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WfStage2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WfStep_Type", propOrder = {
    "wfStepID",
    "processID",
    "processCode",
    "stepCode",
    "currentState",
    "prevWfStepID",
    "createTime",
    "startedBy",
    "startTime",
    "executedBy",
    "executionTime",
    "resultCode",
    "term1",
    "duration1",
    "duration2",
    "mainTerm",
    "mainDuration",
    "copyWfStepID",
    "subWfStepID",
    "canceledBy",
    "cancelTime",
    "cancelReason",
    "objectKind",
    "objectKey",
    "processState",
    "activityCode",
    "parameters",
    "startEndFlag",
    "orgunitType",
    "term2",
    "timout",
    "wfStage1",
    "wfStage2"
})
public class WfStepType {

    @XmlElement(name = "WfStepID")
    protected long wfStepID;
    @XmlElement(name = "ProcessID")
    protected long processID;
    @XmlElement(name = "ProcessCode", required = true)
    protected String processCode;
    @XmlElement(name = "StepCode", required = true)
    protected String stepCode;
    @XmlElement(name = "CurrentState", required = true)
    protected String currentState;
    @XmlElement(name = "PrevWfStepID")
    protected Long prevWfStepID;
    @XmlElement(name = "CreateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createTime;
    @XmlElement(name = "StartedBy")
    protected String startedBy;
    @XmlElement(name = "StartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "ExecutedBy")
    protected String executedBy;
    @XmlElement(name = "ExecutionTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar executionTime;
    @XmlElement(name = "ResultCode")
    protected String resultCode;
    @XmlElement(name = "Term1")
    protected BigInteger term1;
    @XmlElement(name = "Duration1")
    protected BigInteger duration1;
    @XmlElement(name = "Duration2")
    protected BigInteger duration2;
    @XmlElement(name = "MainTerm")
    protected BigInteger mainTerm;
    @XmlElement(name = "MainDuration")
    protected BigInteger mainDuration;
    @XmlElement(name = "CopyWfStepID")
    protected Long copyWfStepID;
    @XmlElement(name = "SubWfStepID")
    protected Long subWfStepID;
    @XmlElement(name = "CanceledBy")
    protected String canceledBy;
    @XmlElement(name = "CancelTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cancelTime;
    @XmlElement(name = "CancelReason")
    protected String cancelReason;
    @XmlElement(name = "ObjectKind", required = true)
    protected String objectKind;
    @XmlElement(name = "ObjectKey", required = true)
    protected String objectKey;
    @XmlElement(name = "ProcessState", required = true)
    protected String processState;
    @XmlElement(name = "ActivityCode", required = true)
    protected String activityCode;
    @XmlElement(name = "Parameters")
    protected String parameters;
    @XmlElement(name = "StartEndFlag")
    protected String startEndFlag;
    @XmlElement(name = "OrgunitType")
    protected String orgunitType;
    @XmlElement(name = "Term2")
    protected BigInteger term2;
    @XmlElement(name = "Timout")
    protected BigInteger timout;
    @XmlElement(name = "WfStage1")
    protected String wfStage1;
    @XmlElement(name = "WfStage2")
    protected String wfStage2;

    /**
     * Gets the value of the wfStepID property.
     * 
     */
    public long getWfStepID() {
        return wfStepID;
    }

    /**
     * Sets the value of the wfStepID property.
     * 
     */
    public void setWfStepID(long value) {
        this.wfStepID = value;
    }

    /**
     * Gets the value of the processID property.
     * 
     */
    public long getProcessID() {
        return processID;
    }

    /**
     * Sets the value of the processID property.
     * 
     */
    public void setProcessID(long value) {
        this.processID = value;
    }

    /**
     * Gets the value of the processCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessCode() {
        return processCode;
    }

    /**
     * Sets the value of the processCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessCode(String value) {
        this.processCode = value;
    }

    /**
     * Gets the value of the stepCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepCode() {
        return stepCode;
    }

    /**
     * Sets the value of the stepCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepCode(String value) {
        this.stepCode = value;
    }

    /**
     * Gets the value of the currentState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentState() {
        return currentState;
    }

    /**
     * Sets the value of the currentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentState(String value) {
        this.currentState = value;
    }

    /**
     * Gets the value of the prevWfStepID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPrevWfStepID() {
        return prevWfStepID;
    }

    /**
     * Sets the value of the prevWfStepID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPrevWfStepID(Long value) {
        this.prevWfStepID = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateTime(XMLGregorianCalendar value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the startedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartedBy() {
        return startedBy;
    }

    /**
     * Sets the value of the startedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartedBy(String value) {
        this.startedBy = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the executedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutedBy() {
        return executedBy;
    }

    /**
     * Sets the value of the executedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutedBy(String value) {
        this.executedBy = value;
    }

    /**
     * Gets the value of the executionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExecutionTime() {
        return executionTime;
    }

    /**
     * Sets the value of the executionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExecutionTime(XMLGregorianCalendar value) {
        this.executionTime = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the term1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTerm1() {
        return term1;
    }

    /**
     * Sets the value of the term1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTerm1(BigInteger value) {
        this.term1 = value;
    }

    /**
     * Gets the value of the duration1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration1() {
        return duration1;
    }

    /**
     * Sets the value of the duration1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration1(BigInteger value) {
        this.duration1 = value;
    }

    /**
     * Gets the value of the duration2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration2() {
        return duration2;
    }

    /**
     * Sets the value of the duration2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration2(BigInteger value) {
        this.duration2 = value;
    }

    /**
     * Gets the value of the mainTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMainTerm() {
        return mainTerm;
    }

    /**
     * Sets the value of the mainTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMainTerm(BigInteger value) {
        this.mainTerm = value;
    }

    /**
     * Gets the value of the mainDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMainDuration() {
        return mainDuration;
    }

    /**
     * Sets the value of the mainDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMainDuration(BigInteger value) {
        this.mainDuration = value;
    }

    /**
     * Gets the value of the copyWfStepID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCopyWfStepID() {
        return copyWfStepID;
    }

    /**
     * Sets the value of the copyWfStepID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCopyWfStepID(Long value) {
        this.copyWfStepID = value;
    }

    /**
     * Gets the value of the subWfStepID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSubWfStepID() {
        return subWfStepID;
    }

    /**
     * Sets the value of the subWfStepID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSubWfStepID(Long value) {
        this.subWfStepID = value;
    }

    /**
     * Gets the value of the canceledBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanceledBy() {
        return canceledBy;
    }

    /**
     * Sets the value of the canceledBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanceledBy(String value) {
        this.canceledBy = value;
    }

    /**
     * Gets the value of the cancelTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCancelTime() {
        return cancelTime;
    }

    /**
     * Sets the value of the cancelTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCancelTime(XMLGregorianCalendar value) {
        this.cancelTime = value;
    }

    /**
     * Gets the value of the cancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * Sets the value of the cancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelReason(String value) {
        this.cancelReason = value;
    }

    /**
     * Gets the value of the objectKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectKind() {
        return objectKind;
    }

    /**
     * Sets the value of the objectKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectKind(String value) {
        this.objectKind = value;
    }

    /**
     * Gets the value of the objectKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectKey() {
        return objectKey;
    }

    /**
     * Sets the value of the objectKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectKey(String value) {
        this.objectKey = value;
    }

    /**
     * Gets the value of the processState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessState() {
        return processState;
    }

    /**
     * Sets the value of the processState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessState(String value) {
        this.processState = value;
    }

    /**
     * Gets the value of the activityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * Sets the value of the activityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityCode(String value) {
        this.activityCode = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameters(String value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the startEndFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartEndFlag() {
        return startEndFlag;
    }

    /**
     * Sets the value of the startEndFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartEndFlag(String value) {
        this.startEndFlag = value;
    }

    /**
     * Gets the value of the orgunitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgunitType() {
        return orgunitType;
    }

    /**
     * Sets the value of the orgunitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgunitType(String value) {
        this.orgunitType = value;
    }

    /**
     * Gets the value of the term2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTerm2() {
        return term2;
    }

    /**
     * Sets the value of the term2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTerm2(BigInteger value) {
        this.term2 = value;
    }

    /**
     * Gets the value of the timout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimout() {
        return timout;
    }

    /**
     * Sets the value of the timout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimout(BigInteger value) {
        this.timout = value;
    }

    /**
     * Gets the value of the wfStage1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfStage1() {
        return wfStage1;
    }

    /**
     * Sets the value of the wfStage1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfStage1(String value) {
        this.wfStage1 = value;
    }

    /**
     * Gets the value of the wfStage2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfStage2() {
        return wfStage2;
    }

    /**
     * Sets the value of the wfStage2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfStage2(String value) {
        this.wfStage2 = value;
    }

}
